### ISSUE TITLE
Error during docker compose up

### ISSUE THREAD

**Issue by mshinoy** [LiamRiddell/Stremio-Server-Raspberry-PI#1]
Device: Raspberry pi 5
OS : Bookworm

Docker compose up has an error. 

stremio-server-1  | SyntaxError: Unexpected token '<'
stremio-server-1  |     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
stremio-server-1  |     at Module._compile (internal/modules/cjs/loader.js:1078:27)
stremio-server-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
stremio-server-1  |     at Module.load (internal/modules/cjs/loader.js:979:32)
stremio-server-1  |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
stremio-server-1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
stremio-server-1  |     at internal/main/run_main_module.js:17:47
stremio-server-1  | /stremio/server.js:1

**Comment by mshinoy** [comment]
Seems downgrading to 

image: stremio/server:v4.20.8

Solved the issue
